const navItems = [
  ['dashboard','Dashboard','◈'],['manuscripts','Manuscripts','▣'],['collaborators','Collaborators','◎'],['journals','Journal Shortlist','◆'],['tasks','Tasks & Deadlines','☑'],['kanban','Editorial Pipeline','▤'],['budget','APC & Funding','◍'],['ethics','Ethics & Files','◌'],['analytics','Analytics','▥'],['settings','Settings','⚙']
];
const progressMap = {'Drafting':18,'Internal Review':35,'Submitted':55,'Major Revision':72,'Minor Revision':82,'Accepted':100,'Rejected':100};
const defaultState = {
  projects:[
    {id:crypto.randomUUID(),title:'AI-Supported Formative Assessment of Inferential Reading in EFL Undergraduate Courses',journal:'Online Learning Journal',status:'Major Revision',priority:'High',deadline:'2026-06-15',apc:0,authors:'Joko Slamet, Co-author 1, Co-author 2',nextAction:'Prepare clean manuscript, tracked changes, and response table.',notes:'Temper causal claims, expand AI feedback mechanism, and clarify internal validity threats.'},
    {id:crypto.randomUUID(),title:'From Accents to Intelligibility: Rethinking Pronunciation Assessment in ELF Classrooms',journal:'TESL-EJ',status:'Drafting',priority:'High',deadline:'2026-07-08',apc:0,authors:'Joko Slamet',nextAction:'Finalize instrument validity and interview protocol.',notes:'Sequential mixed-methods with Indonesian university students.'},
    {id:crypto.randomUUID(),title:'AI as a Pragmatic Coach: Formative Assessment of Politeness and Appropriateness',journal:'JITE: Research',status:'Accepted',priority:'Medium',deadline:'2026-05-30',apc:0,authors:'Joko Slamet, Team',nextAction:'Complete reference corrections and final editorial confirmation.',notes:'Accepted after revision; remaining reference and citation checks.'},
    {id:crypto.randomUUID(),title:'Unpacking Professional Development of EFL Teacher Educators through Academic Writing and Publishing',journal:'JARHE',status:'Internal Review',priority:'Medium',deadline:'2026-06-30',apc:0,authors:'Research Team',nextAction:'Strengthen reflexivity, analytical clarity, and coding transparency.',notes:'Qualitative manuscript with reviewer response table.'}
  ],
  collaborators:[
    {name:'Dr. Joko Slamet',role:'Principal Investigator',email:'jokoslamet@cwcu.ac.id',expertise:'ELT, ESP, AI-mediated learning'},
    {name:'Editorial Partner',role:'Co-author',email:'partner@example.com',expertise:'Mixed methods and statistical reporting'},
    {name:'Method Reviewer',role:'Reviewer',email:'reviewer@example.com',expertise:'PLS-SEM, quasi-experimental design'}
  ],
  journals:[
    {name:'TESL-EJ',quartile:'Q1/Q2 target',fit:'EFL, technology, assessment',apc:'Free / verify current policy',status:'Shortlisted'},
    {name:'Online Learning Journal',quartile:'Scopus-indexed',fit:'Online learning, AI pedagogy',apc:'Free / institutional model',status:'Active'},
    {name:'JITE: Research',quartile:'Scopus-indexed',fit:'Technology education, AI feedback',apc:'Check policy',status:'Accepted pipeline'},
    {name:'IRRODL',quartile:'Q1 target',fit:'AI, online learning, undergraduate EFL',apc:'Check current policy',status:'Future target'}
  ],
  tasks:[
    {title:'Prepare response letter to editor',owner:'Joko',due:'2026-05-31',status:'In Progress'},
    {title:'Check missing in-text citations and references',owner:'Joko',due:'2026-05-29',status:'Urgent'},
    {title:'Export anonymized manuscript package',owner:'Team',due:'2026-06-03',status:'Pending'},
    {title:'Update ethics statement and data availability',owner:'Joko',due:'2026-06-10',status:'Pending'}
  ],
  ethics:[
    {code:'EC-CWCU/08.21/LT.07/2025',project:'Assessment as Learning and Washback',status:'Approved'},
    {code:'5.10.17/STAI-PG.08/LT/2025',project:'EFL formative assessment study',status:'Archived'},
    {code:'6.9.18/STAI-PG.09/LT/2025',project:'AI-mediated EFL study',status:'Ready for manuscript'}
  ]
};
let state = loadState();
let current = 'dashboard';
let searchTerm = '';
function loadState(){try{return JSON.parse(localStorage.getItem('js-rct-pro'))||defaultState}catch{return defaultState}}
function save(){localStorage.setItem('js-rct-pro',JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function statusClass(s){return s==='Accepted'?'good':s==='Rejected'?'bad':s.includes('Revision')?'warn':'brand'}
function priorityClass(p){return p==='High'?'bad':p==='Medium'?'warn':'brand'}
function daysLeft(date){const d=new Date(date); const now=new Date(); return Math.ceil((d-now)/(1000*60*60*24))}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0))}
function filteredProjects(){const q=searchTerm.toLowerCase(); if(!q) return state.projects; return state.projects.filter(p=>[p.title,p.journal,p.status,p.authors,p.nextAction,p.notes].join(' ').toLowerCase().includes(q))}
function initNav(){ $('nav').innerHTML = navItems.map(([id,label,icon])=>`<button data-view="${id}" class="${id===current?'active':''}"><span class="icon">${icon}</span>${label}</button>`).join(''); document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{current=b.dataset.view; $('sidebar').classList.remove('open'); render()}) }
function render(){initNav(); const found=navItems.find(x=>x[0]===current); $('pageTitle').textContent=found?found[1]:'Dashboard'; const views={dashboard,manuscripts,collaborators,journals,tasks,kanban,budget,ethics,analytics,settings}; $('content').innerHTML=views[current](); bindViewEvents()}
function metric(label,value,note){return `<article class="metric card"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`}
function dashboard(){const ps=filteredProjects(); const accepted=state.projects.filter(p=>p.status==='Accepted').length; const urgent=state.tasks.filter(t=>daysLeft(t.due)<=3).length; const budget=state.projects.reduce((a,p)=>a+Number(p.apc||0),0); return `<section class="hero"><div class="hero-main glass"><p class="eyebrow">Premium Research Command Center</p><h3>Integrated manuscript, journal, collaborator, APC, ethics, and deadline management.</h3><p>This exclusive version is redesigned as a professional research operations dashboard. It works fully online on GitHub Pages, stores data locally in the browser, and supports export/import backup.</p><div class="hero-actions"><button class="primary" data-add>+ Add manuscript</button><button class="ghost" data-viewlink="kanban">Open pipeline</button><button class="ghost" data-viewlink="analytics">View analytics</button></div></div><div class="panel"><div class="panel-head"><div><p class="eyebrow">Focus today</p><h3>Immediate actions</h3></div><span class="tag warn">${urgent} urgent</span></div>${state.tasks.slice(0,4).map(t=>`<div class="list-item"><div><strong>${t.title}</strong><p>Owner: ${t.owner} • Due ${t.due}</p></div><span class="tag ${daysLeft(t.due)<=3?'bad':'brand'}">${daysLeft(t.due)} days</span></div>`).join('')}</div></section><section class="metric-grid">${metric('Active manuscripts',state.projects.length,'All research pipelines')}${metric('Accepted outputs',accepted,'Publication-ready progress')}${metric('Collaborators',state.collaborators.length,'Research network')}${metric('Budget estimate',money(budget),'APC and fees')}</section><section class="grid-2"><div class="panel"><div class="panel-head"><div><p class="eyebrow">Manuscript radar</p><h3>Priority manuscripts</h3></div><span class="tag brand">Live</span></div>${projectTable(ps.slice(0,5))}</div><div class="panel"><div class="panel-head"><div><p class="eyebrow">Submission fit</p><h3>Journal shortlist</h3></div><span class="tag brand">${state.journals.length} targets</span></div>${state.journals.map(j=>`<div class="list-item"><div><strong>${j.name}</strong><p>${j.fit}</p></div><span class="tag brand">${j.status}</span></div>`).join('')}</div></section>`}
function projectTable(ps){if(!ps.length)return `<div class="empty">No manuscript found.</div>`; return `<table class="table"><thead><tr><th>Title</th><th>Journal</th><th>Status</th><th>Deadline</th><th></th></tr></thead><tbody>${ps.map(p=>`<tr><td><strong>${p.title}</strong><div class="progress"><i style="width:${progressMap[p.status]||20}%"></i></div></td><td>${p.journal}</td><td><span class="tag ${statusClass(p.status)}">${p.status}</span></td><td>${p.deadline}<br><small>${daysLeft(p.deadline)} days</small></td><td><button class="ghost" data-edit="${p.id}">Edit</button></td></tr>`).join('')}</tbody></table>`}
function manuscripts(){return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">Manuscript Management</p><h3>Complete research portfolio</h3></div><button class="primary" data-add>+ New manuscript</button></div>${projectTable(filteredProjects())}</section>`}
function collaborators(){return `<section class="grid-3">${state.collaborators.map(c=>`<article class="panel"><div class="avatar-row"><div class="avatar">${c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3>${c.name}</h3><p>${c.role}</p></div></div><p><strong>Email:</strong> ${c.email}</p><p><strong>Expertise:</strong> ${c.expertise}</p></article>`).join('')}</section><section class="panel"><p class="eyebrow">Suggested missing menus</p><h3>Collaboration integration</h3><p>This module can be expanded with role assignment, author order, contribution percentage, CRediT roles, file responsibility, and manuscript-specific collaborator mapping.</p></section>`}
function journals(){return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">Journal Intelligence</p><h3>Target journal shortlist</h3></div><button class="ghost" id="exportCsv">Export CSV</button></div><table class="table"><thead><tr><th>Journal</th><th>Quartile</th><th>Scope fit</th><th>APC</th><th>Status</th></tr></thead><tbody>${state.journals.map(j=>`<tr><td><strong>${j.name}</strong></td><td>${j.quartile}</td><td>${j.fit}</td><td>${j.apc}</td><td><span class="tag brand">${j.status}</span></td></tr>`).join('')}</tbody></table></section><section class="grid-2"><div class="panel"><h3>Fit criteria</h3><p>Recommended criteria: Scopus quartile, APC policy, publisher restrictions, review speed, article type, EFL scope fit, technology scope fit, open access policy, and acceptance risk.</p></div><div class="panel"><h3>Submission package checklist</h3><p>Title page, anonymized manuscript, cover letter, highlights, declarations, ethics statement, data availability, author contributions, references, appendices, and response table.</p></div></section>`}
function tasks(){return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">Task Control</p><h3>Deadlines and editorial actions</h3></div><span class="tag warn">Deadline-driven</span></div><div class="list">${state.tasks.map((t,i)=>`<div class="list-item"><div><strong>${t.title}</strong><p>Owner: ${t.owner} • Due ${t.due}</p></div><span class="tag ${daysLeft(t.due)<=3?'bad':t.status==='In Progress'?'warn':'brand'}">${t.status}</span></div>`).join('')}</div></section>`}
function kanban(){const lanes=['Drafting','Internal Review','Submitted','Major Revision']; return `<section class="kanban">${lanes.map(l=>`<div class="lane"><h4>${l}</h4>${state.projects.filter(p=>p.status===l).map(p=>paperCard(p)).join('')||'<p>No item in this lane.</p>'}</div>`).join('')}<div class="lane"><h4>Accepted / Closed</h4>${state.projects.filter(p=>['Accepted','Rejected','Minor Revision'].includes(p.status)).map(p=>paperCard(p)).join('')||'<p>No closed item.</p>'}</div></section>`}
function paperCard(p){return `<article class="paper-card"><h4>${p.title}</h4><p>${p.journal}</p><div class="progress"><i style="width:${progressMap[p.status]||20}%"></i></div><div class="meta"><span class="tag ${statusClass(p.status)}">${p.status}</span><span class="tag ${priorityClass(p.priority)}">${p.priority}</span><span class="tag brand">${daysLeft(p.deadline)} days</span></div></article>`}
function budget(){const total=state.projects.reduce((a,p)=>a+Number(p.apc||0),0); return `<section class="metric-grid">${metric('Total APC estimate',money(total),'Across portfolio')}${metric('Free APC targets',state.projects.filter(p=>Number(p.apc||0)===0).length,'No-fee / pending')}${metric('Highest cost',money(Math.max(0,...state.projects.map(p=>Number(p.apc||0)))),'Single manuscript')}${metric('Projects tracked',state.projects.length,'Budget base')}</section><section class="panel"><div class="panel-head"><div><p class="eyebrow">Budget Registry</p><h3>APC and funding overview</h3></div></div><table class="table"><thead><tr><th>Manuscript</th><th>Journal</th><th>Status</th><th>APC estimate</th></tr></thead><tbody>${state.projects.map(p=>`<tr><td><strong>${p.title}</strong></td><td>${p.journal}</td><td><span class="tag ${statusClass(p.status)}">${p.status}</span></td><td>${money(p.apc)}</td></tr>`).join('')}</tbody></table></section>`}
function ethics(){return `<section class="grid-3">${state.ethics.map(e=>`<article class="panel"><p class="eyebrow">IRB / Ethics Code</p><h3>${e.code}</h3><p>${e.project}</p><span class="tag good">${e.status}</span></article>`).join('')}</section><section class="panel"><h3>Professional document vault design</h3><p>Recommended integrated menus: ethics approval, informed consent, data availability, anonymization log, instrument appendix, raw-data storage note, and submission declarations. GitHub Pages cannot store uploaded files privately, so sensitive files should remain in Google Drive, institutional repository, or secure cloud storage.</p></section>`}
function analytics(){const counts={}; state.projects.forEach(p=>counts[p.status]=(counts[p.status]||0)+1); const max=Math.max(1,...Object.values(counts)); const deadlineRisk=state.projects.filter(p=>daysLeft(p.deadline)<=14).length; return `<section class="metric-grid">${metric('Deadline risk',deadlineRisk,'Due in ≤14 days')}${metric('Revision load',state.projects.filter(p=>p.status.includes('Revision')).length,'Active revision work')}${metric('Submission stage',state.projects.filter(p=>p.status==='Submitted').length,'Awaiting decision')}${metric('Completion rate',Math.round((state.projects.filter(p=>p.status==='Accepted').length/state.projects.length)*100)+'%','Accepted / total')}</section><section class="grid-2"><div class="panel"><div class="panel-head"><div><p class="eyebrow">Status analytics</p><h3>Portfolio distribution</h3></div></div><div class="chart-bars">${Object.entries(counts).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar"><i style="width:${(v/max)*100}%"></i></div><strong>${v}</strong></div>`).join('')}</div></div><div class="panel"><p class="eyebrow">Executive diagnosis</p><h3>What still needs integration?</h3><p>The biggest missing professional features were separated menus, project-specific tasking, journal intelligence, budget monitoring, ethics tracking, import/export backup, and an integrated editorial pipeline. This version adds all of them in one dashboard.</p></div></section>`}
function settings(){return `<section class="grid-2"><div class="settings-card"><h3>Data storage</h3><p>This app is offline-first. Data is saved in your current browser through localStorage. Use Export JSON regularly for backup.</p><button class="ghost" id="resetData">Reset demo data</button></div><div class="settings-card"><h3>Deployment</h3><p>Upload all extracted files to GitHub Pages. The permanent link will use your repository name and GitHub username.</p><button class="ghost" id="exportJson2">Export backup</button></div></section><section class="panel"><h3>Recommended future premium integrations</h3><p>For full cloud synchronization, multi-user login, admin dashboard, file uploads, and shared database access, this static version should later be converted into a full-stack app using Supabase/Firebase or a Node.js backend.</p></section>`}
function openModal(project){$('modalBackdrop').classList.add('show'); $('modalBackdrop').setAttribute('aria-hidden','false'); $('modalTitle').textContent=project?'Edit Manuscript':'Add Manuscript'; const f=$('projectForm'); f.reset(); if(project){Object.keys(project).forEach(k=>{if(f.elements[k]) f.elements[k].value=project[k]})} else {f.elements.deadline.value=new Date(Date.now()+14*86400000).toISOString().slice(0,10); f.elements.status.value='Drafting'; f.elements.priority.value='High'}}
function closeModal(){ $('modalBackdrop').classList.remove('show'); $('modalBackdrop').setAttribute('aria-hidden','true') }
function bindViewEvents(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openModal()); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(state.projects.find(p=>p.id===b.dataset.edit))); document.querySelectorAll('[data-viewlink]').forEach(b=>b.onclick=()=>{current=b.dataset.viewlink; render()}); const csv=$('exportCsv'); if(csv) csv.onclick=exportCSV; const reset=$('resetData'); if(reset) reset.onclick=()=>{if(confirm('Reset all local data to the professional demo version?')){state=structuredClone(defaultState); save(); render()}}; const ej2=$('exportJson2'); if(ej2) ej2.onclick=exportJSON}
$('menuToggle').onclick=()=>$('sidebar').classList.toggle('open'); $('quickAdd').onclick=()=>openModal(); $('closeModal').onclick=closeModal; $('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}; $('globalSearch').oninput=e=>{searchTerm=e.target.value; render()}; $('exportJson').onclick=exportJSON; $('importJson').onchange=importJSON;
$('projectForm').onsubmit=e=>{e.preventDefault(); const fd=new FormData(e.target); const p=Object.fromEntries(fd.entries()); p.apc=Number(p.apc||0); if(p.id){const idx=state.projects.findIndex(x=>x.id===p.id); state.projects[idx]=p}else{p.id=crypto.randomUUID(); state.projects.unshift(p)} save(); closeModal(); render()};
function download(name,content,type='application/json'){const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url)}
function exportJSON(){download('JS-Research-Collaboration-Tracker-Pro-Backup.json',JSON.stringify(state,null,2))}
function importJSON(e){const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{try{state=JSON.parse(reader.result); save(); render(); alert('Backup imported successfully.')}catch{alert('Invalid JSON backup file.')}}; reader.readAsText(file)}
function exportCSV(){const rows=[['Journal','Quartile','Fit','APC','Status'],...state.journals.map(j=>[j.name,j.quartile,j.fit,j.apc,j.status])]; download('journal-shortlist.csv',rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
render();
